### ISSUE TITLE
evol : elasticsearch or mongo

### ISSUE THREAD

**Issue by AlbanMinassian** [rudijs/koa-json-logger#2]
How use alternative stream like elasticsearch or mongodb (https://www.npmjs.com/browse/keyword/Bunyan) ?

Thank
Ami44

**Comment by rudijs** [comment]
Hi,

Hrm .. that's an interesting question, but I'm sorry I don't have an answer for you.

I do put my logs into elasticsearch, but I'm using a different stack.

From the log file I use logstash to read the logs and send it on to elasticsearch (the ELK stack).

I don't think I'll be much more help for this issue beyond this reply I'm afraid - you might be on your own to figure this one out.

**Comment by AlbanMinassian** [comment]
Thank
